### ISSUE TITLE
Nightly builds failing

### ISSUE THREAD

**Issue by IndrajeetPatil** [Open-Systems-Pharmacology/OSPSuite-R#1017]
Seem to be due to two vignettes which can't be built:

```r
* creating vignettes ... ERROR
--- re-building 'create-individual.Rmd' using rmarkdown
Quitting from lines 30-49 (create-individual.Rmd) 
Error: processing vignette 'create-individual.Rmd' failed with diagnostics:
Type:    System.TypeLoadException
Message: Method 'AskForInput' in type 'PKSim.CLI.Core.MinimalImplementations.CLIDialogCreator' from assembly 'PKSim.CLI.Core, Version=11.0.150.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method:  Void registerMinimalImplementations(OSPSuite.Utility.Container.IContainer)
Stack trace:
   at PKSim.R.Bootstrap.ApplicationStartup.registerMinimalImplementations(IContainer container)
   at PKSim.R.Bootstrap.ApplicationStartup.performInitialization()
   at PKSim.R.Bootstrap.ApplicationStartup.Initialize()
   at PKSim.R.Api.InitializeOnce()
--- failed re-building 'create-individual.Rmd'
--- re-building 'create-run-population.Rmd' using rmarkdown
Quitting from lines 38-61 (create-run-population.Rmd) 
Error: processing vignette 'create-run-population.Rmd' failed with diagnostics:
Type:    System.TypeLoadException
Message: Method 'AskForInput' in type 'PKSim.CLI.Core.MinimalImplementations.CLIDialogCreator' from assembly 'PKSim.CLI.Core, Version=11.0.150.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method:  Void registerMinimalImplementations(OSPSuite.Utility.Container.IContainer)
Stack trace:
   at PKSim.R.Bootstrap.ApplicationStartup.registerMinimalImplementations(IContainer container)
   at PKSim.R.Bootstrap.ApplicationStartup.performInitialization()
   at PKSim.R.Bootstrap.ApplicationStartup.Initialize()
   at PKSim.R.Api.InitializeOnce()
--- failed re-building 'create-run-population.Rmd'
```

**Comment by msevestre** [comment]
This is because we need to update PKSim.

**Comment by PavelBal** [comment]
@Yuri05 Could you trigger a new build with updated Core DLLs? This this prevents us from moving forward.

**Comment by Yuri05** [comment]
> @Yuri05 Could you trigger a new build with updated Core DLLs? This this prevents us from moving forward.

tried, but build failed again

**Comment by msevestre** [comment]
I need to update PKSim. Just comment out the PKSim test for now and you will be good to go

**Comment by msevestre** [comment]
Will turn off test in #1026 

We need to turn then back on when fixing this issue

**Comment by msevestre** [comment]
new nigthly build triggered
![image](https://user-images.githubusercontent.com/1041237/179693991-337b7694-32a0-4761-ab94-e6128624a081.png)

**Comment by msevestre** [comment]
ok I need to not generate vignettes also

**Comment by IndrajeetPatil** [comment]
The latest build failure might be a false positive. Looks like AppVeyor couldn't access CRAN to download the needed packages.

Re-triggering the build might succeed.

**Comment by msevestre** [comment]
yep
we are good

**Comment by msevestre** [comment]
Can you then create a new issue to enable the PKSim tests again.?

**Comment by PavelBal** [comment]
Done

**Comment by IndrajeetPatil** [comment]
This is happening again:

```r
* creating vignettes ... ERROR
--- re-building 'create-individual.Rmd' using rmarkdown
Quitting from lines 30-49 (create-individual.Rmd) 
Error: processing vignette 'create-individual.Rmd' failed with diagnostics:
Type:    System.TypeLoadException
Message: Method 'AskForInput' in type 'PKSim.CLI.Core.MinimalImplementations.CLIDialogCreator' from assembly 'PKSim.CLI.Core, Version=11.0.150.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method:  Void registerMinimalImplementations(OSPSuite.Utility.Container.IContainer)
Stack trace:
   at PKSim.R.Bootstrap.ApplicationStartup.registerMinimalImplementations(IContainer container)
   at PKSim.R.Bootstrap.ApplicationStartup.performInitialization()
   at PKSim.R.Bootstrap.ApplicationStartup.Initialize()
   at PKSim.R.Api.InitializeOnce()
```

**Comment by msevestre** [comment]
This can't be happening again. I have commented out the tests. What build are you looking at? 
IF you are looking at the R 3.6, of course it will fail but this we do not use the packages here anyways.

**Comment by PavelBal** [comment]
Also with the 11.1 PK-Sim nighty, `initPKSim()` does not work:

```
> initPKSim(pksimFolderPath = "c:\\Program Files\\Open Systems Pharmacology\\PK-Sim 11.1\\")
Error in rClr::clrCallStatic("PKSim.R.Api", "InitializeOnce") : 
  Type:    System.TypeLoadException
Message: Method 'AskForInput' in type 'PKSim.CLI.Core.MinimalImplementations.CLIDialogCreator' from assembly 'PKSim.CLI.Core, Version=11.0.150.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method:  Void registerMinimalImplementations(OSPSuite.Utility.Container.IContainer)
Stack trace:
   at PKSim.R.Bootstrap.ApplicationStartup.registerMinimalImplementations(IContainer container)
   at PKSim.R.Bootstrap.ApplicationStartup.performInitialization()
   at PKSim.R.Bootstrap.ApplicationStartup.Initialize()
   at PKSim.R.Api.InitializeOnce()
```

I do not understand why the version is marked as 11.0.150.0?

**Comment by msevestre** [comment]
Is this local or what?

**Comment by PavelBal** [comment]
Yes, I tried this local with the nightly PK-Sim.

**Comment by msevestre** [comment]
Hum... something is off. Arey ou sure you are using version 11.1 of PKSim?

**Comment by msevestre** [comment]
https://ci.appveyor.com/project/open-systems-pharmacology-ci/pk-sim/build/artifacts

**Comment by PavelBal** [comment]
> Arey ou sure you are using version 11.1 of PKSim?

Yes, absolutely.

**Comment by PavelBal** [comment]
It did not work because Windwos blocks loading of DLLs if they were downloaded as a zip.... omg this will drive me crazy.

**Comment by msevestre** [comment]
What ?? Since when
I have no problem doing this using win 11

**Comment by Yuri05** [comment]
depends on the virus scanner. with some of them indeed - no chance, in the portable version every single dll is deleted
