### ISSUE TITLE
Fix build failures

### ISSUE THREAD

**Issue by IndrajeetPatil** [Open-Systems-Pharmacology/OSPSuite-R#1022]
Seems to be related to changes upstream:

# Failing example

```r
> xlsFilePath <- system.file("extdata", "CompiledDataSet.xlsx", package = "ospsuite")
> importerConfiguration <- createImporterConfigurationForFile(xlsFilePath)
> importerConfiguration$sheets <- "TestSheet_1"
> 
> dataSets <- loadDataSetsFromExcel(
+   xlsFilePath = xlsFilePath,
+   importerConfigurationOrPath = importerConfiguration,
+   importAllSheets = FALSE
+ )
Error in rClr::clrCall(dataImporterTask, "ImportExcelFromConfiguration",  : 
  Type:    System.NullReferenceException
Message: Object reference not set to an instance of an object.
Method:  Boolean convertParsedDataColumnAndReturnWarningFlag(OSPSuite.Core.Domain.Data.DataRepository, System.Collections.Generic.KeyValuePair`2[OSPSuite.Infrastructure.Import.Core.ExtendedColumn,System.Collections.Generic.IList`1[OSPSuite.Infrastructure.Import.Core.SimulationPoint]], System.String)
Stack trace:
   at OSPSuite.Infrastructure.Import.Core.Mappers.DataSetToDataRepositoryMapper.convertParsedDataColumnAndReturnWarningFlag(DataRepository dataRepository, KeyValuePair`2 columnAndData, String fileName)
   at OSPSuite.Infrastructure.Import.Core.Mappers.DataSetToDataRepositoryMapper.ConvertImportDataSet(ImportedDataSet dataSet)
   at OSPSuite.Infrastructure.Import.Services.Importer.DataSourceToDataSets(IDataSource dataSource, IReadOnlyList`1 metaDataCategories, DataImporterSettings dataImporterSettings, String id)
   at OSPSuite.Infrastructure.Import.Services.Importer.Im
Calls: loadDataSetsFromExcel -> <Anonymous>
Execution halted
```

# Failing tests

```r
  1/1 mismatches
  x[1]: "MW"
  y[1]: "Concentration (mass)[ng/ml]"
  -- Failure (test-utilities-data-importer-configuration.R:13:3): It can create a DataImporterConfiguration from a XLS file --
  importerConfiguration$measurementDimension not equal to ospDimensions$`Concentration (mass)`.
  target is NULL, current is character
  -- Failure (test-utilities-data-importer-configuration.R:14:3): It can create a DataImporterConfiguration from a XLS file --
  importerConfiguration$measurementUnit not equal to "ng/ml".
  1/1 mismatches
  x[1]: "?"
  y[1]: "ng/ml"
  
  [ FAIL 3 | WARN 4 | SKIP 5 | PASS 962 ]
  Error: Test failures
  Execution halted
```

**Comment by IndrajeetPatil** [comment]
@PavelBal, @Yuri05, @msevestre Any ideas on what's the source of this?

**Comment by IndrajeetPatil** [comment]
Never mind. Pavel clarified [here](https://github.com/Open-Systems-Pharmacology/OSPSuite-R/pull/1021#issuecomment-1187247902).
