### ISSUE TITLE
`setParameterValuesByPath()` fails if path contains a `*`

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite-R#1139]
For parameter `"Organism|R*T"`, it is impossible to call `setParameterValuesByPath()` because it considers it as a wildcard, while `getParameter()` works.

```
simFilePath <- system.file("extdata", "Aciclovir.pkml", package = "ospsuite")
sim <- loadSimulation(simFilePath)
paramPath <- "Organism|R*T"
param <- getParameter(path = paramPath, container = sim)

setParameterValuesByPath(parameterPaths = paramPath, values = 1, simulation = sim)
```

throws an error:

```
Error in rClr::clrCall(task, "SetValueByPath", simulation$ref, path, value, : 
Type: OSPSuite.Utility.Exceptions.OSPSuiteException
Message: Accessing value by path is not supported for path containing wildcard (Organism|R*T)
Method: OSPSuite.Core.Domain.IQuantity singleQuantityByPath(OSPSuite.Core.Domain.IModelCoreSimulation, System.String, Boolean)
Stack trace:
at OSPSuite.R.Services.ContainerTask.singleQuantityByPath(IModelCoreSimulation simulation, String path, Boolean throwIfNotFound)
at OSPSuite.R.Services.ContainerTask.SetValueByPath(IModelCoreSimulation simulation, String path, Double value, Boolean throwIfNotFound)
3.
rClr::clrCall(task, "SetValueByPath", simulation$ref, path, value, 
stopIfNotFound) at utilities-quantity.R#175
2.
setQuantityValuesByPath(quantityPaths = parameterPaths, values = values, 
simulation = simulation, units = units, stopIfNotFound = stopIfNotFound) at utilities-parameter.R#128
1.
setParameterValuesByPath(parameterPaths = paramPath, values = 1, 
simulation = sim)
```

The method `SetValueByPath()` from `OSPSuite.R.Services.ContainerTask` should not stop when an`*` is found but simply not consider it as a wildcard.

To be fixed in Core, I think.

**Comment by PavelBal** [comment]
@msevestre I cannot assign issues to Rob - he must be added to Rdev team first, I guess?

**Comment by PavelBal** [comment]
@msevestre @Yuri05 Any idea how this should be handled?

**Comment by Yuri05** [comment]
For the future, we should forbid using `*` in entity names. 
For already existing parameters:
* option 1: we ignore the situation. There are only 3 parameters containing `*` in the current PK-Sim models. And for all 3 changing them does not make any sense.
![grafik](https://github.com/Open-Systems-Pharmacology/OSPSuite-R/assets/25061876/e81f3c2b-2b1f-4557-bf98-766c12bc0b69)
* option 2: we support escaping in paths (e.g. `\*` for `*` and `\\` for `\`)

**Comment by PavelBal** [comment]
Option 2 is probably a cleaner solution. Both options must be implemented in Core, right?
