### ISSUE TITLE
`SimulationBatch` does not return a propper error

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite-R#1169]
[ospsuite-r_noErrorSimulationBatch.zip](https://github.com/Open-Systems-Pharmacology/OSPSuite-R/files/10207207/ospsuite-r_noErrorSimulationBatch.zip)

A simulation that is poorly defined (negative clearance value) fails in MoBi with the error:

![image](https://user-images.githubusercontent.com/25903040/207027018-24bdebd4-1ce0-4fd9-b45d-eed5279eaf6b.png)

In R with `runSimulations()` the error is correct:

```
simPath <- "../ErrorSim.pkml"

sim <- loadSimulation(simPath, loadFromCache = TRUE)

simResults <- runSimulation(sim)
```

```
Error in rClr::clrCall(simulationRunner, "Run", simulationRunArgs) : 
Type: OSPSuite.Utility.Exceptions.OSPSuiteException
Message: Simulation run failed: some variables became negative when trying to reach t=1. There are different possible reasons for this:

- Solver tolerances are too high. Please reduce the absolute and relative tolerances by one order of magnitude (e.g. from 1E-9 to 1E-10) and restart the simulation.
- Some variables which are allowed to be negative were defined as non-negative.
- Model is not properly established (e.g. the kinetic should be k*[A] but was defined as k*[B] etc.)

The following variables became negative :
Rat_generic_Schmitt_Schmitt|Organism|Liver|Periportal|Intracellular|Generic_compound-Undefined Liver Metabolite

Method: Void RunSimulation()
Stack trace:
at OSPSuite.SimModel.Simulation.RunSimulation()
at OSPSuite.Core.Domain.Services.SimModelManager.simulate()
at OSPSuite.Core.Domain.Services.SimModelManager.doIfNotCanceled(Action actionToExecute)
at OSPSuite.Core.Domain.Services.SimMod
4.
rClr::clrCall(simulationRunner, "Run", simulationRunArgs) at utilities-simulation.R#231
3.
.runSingleSimulation(simulation = simulations[[1]], simulationRunOptions = simulationRunOptions, 
population = population, agingData = agingData) at utilities-simulation.R#183
2.
runSimulations(simulations = simulation, population = population, 
agingData = agingData, simulationRunOptions = simulationRunOptions) at utilities-simulation.R#126
1.
runSimulation(sim)
```

Running a simulation batch only shows warnings and returns `NULL` as results:

```
simPath <- "../ErrorSim.pkml"

sim <- loadSimulation(simPath, loadFromCache = TRUE)

# Get the paths of all molecules in the simulation
moleculePaths <- getAllMoleculePathsIn(container = sim)
# Get the current intial values of all molecules
moleculesStartValues <- getQuantityValuesByPath(quantityPaths = moleculePaths,
                                                simulation = sim)
# Create simulation batch and define all molecules as variable
simBatch <- createSimulationBatch(simulation = sim,
                                  moleculesOrPaths = moleculePaths)
# Add run values
simBatch$addRunValues(initialValues = moleculesStartValues)

results <- runSimulationBatches(simBatch)
```

```
[CVODES WARNING]  CVode
  Internal t = 598.713 and h = 5.99766e-17 are such that t + h = t on the next step. The solver will continue anyway.


[CVODES WARNING]  CVode
  The above warning has been issued mxhnil times and will not be issued again for this problem.

Warning message:
In .getConcurrentSimulationRunnerResults(results = results, resultsIdSimulationIdMap = resultsIdSimulationBatchIdMap,  :
  The time column is not strictly monotonically increasing (152.45 h is immediately followed by 152.183333333333 h).
Ensure that time always increases (e.g. 0.5, 1, 2, 4 hours).

> results
$`babfa56c-f909-44e7-af3f-780ae8cf2f9f`
$`babfa56c-f909-44e7-af3f-780ae8cf2f9f`$`b565d574-4739-467a-ab07-3b02ec5d5815`
NULL
```

**Comment by rwmcintosh** [comment]
@PavelBal update Core when Open-Systems-Pharmacology/OSPSuite.Core#1835 is merged
