### ISSUE TITLE
Simulation running in MoBi but failing in R

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite-R#1170]
[ospsuite-r_Simulation_running_in_MoBi_but_failing_in_R.zip](https://github.com/Open-Systems-Pharmacology/OSPSuite-R/files/10216755/ospsuite-r_Simulation_running_in_MoBi_but_failing_in_R.zip)

The attached simulation runs in MoBi but fails in R. Interesting case @msevestre @Yuri05 @rwmcintosh ;)

```
> simPath <- "D:\\Downloads\\158966-92-8_C21_D1_IV_single_D1_OSP_5411.pkml"
> sim <- loadSimulation(simPath)
> simResults <- runSimulation(sim)
```

```
[CVODES ERROR]  CVode
  At t = 0 and h = 3.8147e-16, the corrector convergence test failed repeatedly or with |h| = hmin.


[CVODES ERROR]  CVode
  At t = 0 and h = 3.8147e-16, the corrector convergence test failed repeatedly or with |h| = hmin.

 Error in rClr::clrCall(simulationRunner, "Run", simulationRunArgs) : 
Type: OSPSuite.Utility.Exceptions.OSPSuiteException
Message: Error solving ODE at time t=1: Either convergence test failures occurred too many times during one internal time step, or with |h| = hmin (CV_CONV_FAILURE)
Method: Void RunSimulation()
Stack trace:
at OSPSuite.SimModel.Simulation.RunSimulation()
at OSPSuite.Core.Domain.Services.SimModelManager.simulate()
at OSPSuite.Core.Domain.Services.SimModelManager.doIfNotCanceled(Action actionToExecute)
at OSPSuite.Core.Domain.Services.SimModelManager.RunSimulation(IModelCoreSimulation simulation, SimulationRunOptions simulationRunOptions)
at OSPSuite.R.Services.SimulationRunner.run(IModelCoreSimulation simulation, SimulationRunOptions simulationRunOptions)
at OSPSuite.R.Services.SimulationRunner.Run(SimulationRunArgs simulationRunArgs)
4.
rClr::clrCall(simulationRunner, "Run", simulationRunArgs) at utilities-simulation.R#231
3.
.runSingleSimulation(simulation = simulations[[1]], simulationRunOptions = simulationRunOptions, 
population = population, agingData = agingData) at utilities-simulation.R#183
2.
runSimulations(simulations = simulation, population = population, 
agingData = agingData, simulationRunOptions = simulationRunOptions) at utilities-simulation.R#126
1.
runSimulation(sim)
```

**Comment by Yuri05** [comment]
which is due to the fact that fu=0
![grafik](https://user-images.githubusercontent.com/25061876/207296286-a77db1c2-e0c0-47d6-a40a-45d44d69e354.png)

**Comment by Yuri05** [comment]
So in fact this simulation is invalid. 
It runs indeed in MoBi 11.0 (probably due to the missing check of parameter initial values) - did you use MoBi 11.0?
I guess in ospsuite-R 11.0 it would run as well - did you use ospsuite-R 11.1?
Anyways: the simulation is corrupted and should fail, so MoBi 11.1 and ospsuite 11.1 both behave as expected.

**Comment by PavelBal** [comment]
Thanks @Yuri05 ! can be closed
