### ISSUE TITLE
Data importer errors are not propagated to R

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite-R#1186]
Trying to load the uploaded sheet with the configuration in PK-Sim shows an error that no unit for Measurement is defined:

![image](https://user-images.githubusercontent.com/25903040/214018278-cc4ed0e2-01c4-4a32-8127-a06e95ea5fbb.png)

Doing the same in R does not produce an error:

```
importConfig <- loadDataImporterConfiguration("esqlabs_dataImporter_configuration.xml")
dataSets <- loadDataSetsFromExcel(xlsFilePath = "MissingTimeUnit.xlsx",
                                  importerConfigurationOrPath = importConfig,
                                   importAllSheets = TRUE)
```

The imported data set is corrupt:

```
> dataSets
$`PTU_Mendes_2014__Human_PeripheralVenousBlood_Plasma_100 [mg] PTU_po_fasted`
DataSet: 
   Name: PTU_Mendes_2014__Human_PeripheralVenousBlood_Plasma_100 [mg] PTU_po_fasted 
   X dimension:  
 Error in rClr::clrCallStatic(typename, methodName, self$ref) : 
Type: System.NullReferenceException
Message: Object reference not set to an instance of an object.
Method: OSPSuite.Core.Domain.UnitSystem.Unit get_DisplayUnit()
Stack trace:
at OSPSuite.Core.Domain.Data.DataColumn.get_DisplayUnit()
at OSPSuite.Core.Domain.WithDisplayUnitExtensions.DisplayUnitName(IWithDisplayUnit withDisplayUnit)
8.
rClr::clrCallStatic(typename, methodName, self$ref) at dot-net-wrapper.R#69
7.
private$wrapExtensionMethod(WITH_DISPLAY_UNIT_EXTENSION, "DisplayUnitName", 
"displayUnit", value) at data-column.R#32
6.
(function (value) 
{
if (missing(value)) {
return(private$wrapExtensionMethod(WITH_DISPLAY_UNIT_EXTENSION, ... at data-set.R#48
5.
(function (value) 
{
if (missing(value)) {
return(private$.xColumn$displayUnit) ... at printable.R#40
4.
private$printLine("X unit", self$xUnit) at data-set.R#277
3.
.subset2(x, "print")(...)
2.
print.R6(x)
1.
(function (x, ...) 
UseMethod("print"))(x)

```

I also have seen other use cases where the error in R is much less informative than the corresponding error in PK-Sim, so I assume some messages are not properly forwarded.

**Comment by PavelBal** [comment]
@rwmcintosh @georgeDaskalakis Assigning you to this, must be a Core issue.

**Comment by svavil** [comment]
This might be less important for external users, but this slows down internal development.

**Comment by PavelBal** [comment]
https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/issues/2724
