### ISSUE TITLE
12.0 nightly build fails

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite-R#1391]
https://ci.appveyor.com/project/open-systems-pharmacology-ci/ospsuite-r/builds/49589405
```
[197s] ERROR
Errors in running code in vignettes:
when running code in 'set-values.Rmd'
  ...
   Path: Organism|StateVariable_Parameter 
   Value: 10.00 
   isConstant: TRUE 
   isStateVariable: FALSE 
> stateVariableParam$isStateVariable <- TRUE
  When sourcing 'set-values.R':
Error: Creating a RHS Formula is not supported at the moment. This should be done in MoBi.
Execution halted
when running code in 'table-parameters.Rmd'
  ...
  When sourcing 'table-parameters.R':
Error: Type:    OSPSuite.Core.Domain.ValuePointAlreadyExistsForPointException
Message: A point for x=0 was already added with y=1
Method:  Int32 AddPoint(OSPSuite.Core.Domain.Formulas.ValuePoint)
Stack trace:
   at OSPSuite.Core.Domain.Formulas.TableFormula.AddPoint(ValuePoint point)
   at OSPSuite.Core.Domain.Formulas.TableFormula.AddPoint(Double x, Double y)
Execution halted
when running code in 'unit-conversion.Rmd'
  ...
  When sourcing 'unit-conversion.R':
Error: Type:    OSPSuite.Utility.Exceptions.OSPSuiteException
Message: Unit 'kg/m²' is not defined in dimension 'BMI'.
Method:  Double[] convertToBaseUnit(OSPSuite.Core.Domain.UnitSystem.IDimension, System.String, System.Nullable`1[System.Double], Double[])
Stack trace:
   at OSPSuite.R.Services.DimensionTask.convertToBaseUnit(IDimension dimension, String displayUnit, Nullable`1 molWeight, Double[] valuesInDisplayUnit)
   at OSPSuite.R.Services.DimensionTask.ConvertToBaseUnit(String dimensionName, String displayUnit, Double valueInDisplayUnit)
```

**Comment by Yuri05** [comment]
with the last changes, only 1 error remains in nightly build: @PavelBal @Felixmil 

```
Errors in running code in vignettes:
when running code in 'unit-conversion.Rmd'
  ...
  When sourcing 'unit-conversion.R':
Error: Type:    OSPSuite.Utility.Exceptions.OSPSuiteException
Message: Unit 'kg/m²' is not defined in dimension 'BMI'.
```

**Comment by Felixmil** [comment]
I cannot reproduce locally. Building the vignette do no lead to any error on my side.

**Comment by PavelBal** [comment]
Yes, you have to set `error = TRUE, purl = FALSE}` for this chunk, as you did for the other two vignettes.

**Comment by PavelBal** [comment]
Ah wait

**Comment by PavelBal** [comment]
Something is wrong with unicode... But I have no idea what.

**Comment by Felixmil** [comment]
> Yes, you have to set `error = TRUE, purl = FALSE}` for this chunk, as you did for the other two vignettes.

No because this chunk is not supposed to return error. So if there is an actual error, it should stop.


> Something is wrong with unicode... But I have no idea what.
Yes seems so. Maybe from the OSP Dimensions and Units submodule ?

**Comment by Felixmil** [comment]
Additional data:

`"\U00B2"` is unicode for ²

```r
> ospUnits$BMI[[1]]
[1] "kg/m²"
> ospUnits$BMI[[1]] == "kg/m\U00B2"
[1] TRUE
> ospUnits$BMI[[1]] == "kg/m²"
[1] FALSE
```

**Comment by PavelBal** [comment]
On my machine its:

```
> ospUnits$BMI[[1]] == "kg/m²"
[1] TRUE
```

**Comment by Felixmil** [comment]
Nevermind, I just restarted R session and now it's also `TRUE`

**Comment by msevestre** [comment]
>Something is wrong with unicode... But I have no idea what.

Unicode is wrong

**Comment by Felixmil** [comment]
Apparently not in R 4.3.3 (cf #1397)

**Comment by PavelBal** [comment]
Obsolete with GHA
