### ISSUE TITLE
createIndividual: error message truncated

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/OSPSuite-R#347]
https://github.com/Open-Systems-Pharmacology/OSPSuite-R/issues/345

**Comment by msevestre** [comment]
@Yuri05 @PavelBal  This is an issue in general with rCLR I believe. Error messages are being truncated.
For the next version, we should come up with a better way to show managed error messages (e.g exception coming from PKSIm or Core that are thrown by us)

I don't want to implement something quickly that does not make sense.


Example of truncated message

```
Exception
Message: Could not create individuals with given constraint:

Method:  Void optimizeVolumes(PKSim.Core.Model.Individual, OSPSuite.Core.Maths.Random.RandomGenerator)
Stack trace:
   at PKSim.Core.Services.CreateIndividualAlgorithm.optimizeVolumes(Individual individual, RandomGenerator randomGenerator)
   at PKSim.Core.Services.CreateIndividualAlgorithm.distributeParameterFor(Individual individual, RandomGenerator randomGenerator, Action`2 action)
   at PKSim.Core.Services.CreateIndividualAlgorithm.Optimize(Individual individual)
   at PKSim.Core.Model.IndividualFactory.CreateAndOptimizeFor(OriginData originData, Nullable`1 seed)
   at PKSim.R.Services.IndividualFactory.CreateIndividual(IndividualCharacteristics individualCharacteristics)
```

**Comment by msevestre** [comment]
Maybe the signature of the R API could change to return an structure: e.g. instead of returning the data, we would have a result object: For ex
{
  data: individual,
  error: xxxx
}

if error is not NULL then there is an error 

Let's think about it

**Comment by PavelBal** [comment]
I do not really like such "nester" output structures. Also, having always to check whether there is an error or not before using the output. However, such a check could be performed before returning the output to the user.

**Comment by msevestre** [comment]
@PavelBal Absolutely. This would just be for the direct R API calls to .NET and should not be visible to the user of the lib
