### ISSUE TITLE
Better error message when toUnit gets wrong unit

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite-R#510]
Currently, if `toUnit` or `toBaseUnit` cannot convert the value because the unit is not valid for the dimension, following error is thrown: 

```
toUnit(quantityOrDimension = ospDimensions$`Dose per body weight`, values = 1, targetUnit = "g/kg")
Error in rClr::clrCall(dimensionTask, "ConvertToUnit", dimension, targetUnit,  : 
  Type:    System.InvalidOperationException
Message: Sequence contains no matching element
Method:  TSource First[TSource](System.Collections.Generic.IEnumerable`1[TSource], System.Func`2[TSource,System.Boolean])
Stack trace:
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at OSPSuite.R.Services.DimensionTask.convertToUnit(IDimension dimension, String targetUnit, Nullable`1 molWeight, Double[] valuesInBaseUnit)
   at OSPSuite.R.Services.DimensionTask.ConvertToUnit(String dimensionName, String targetUnit, Double valueInBaseUnit)
```

More informative error should be either coming from .NET, or `toUnit` and `toBaseUnit` should check `validateUnit` first.

**Comment by IndrajeetPatil** [comment]
The example you are using doesn't seem to produce error anymore:

``` r
library(ospsuite)
toUnit(quantityOrDimension = ospDimensions$`Dose per body weight`, values = 1, targetUnit = "g/kg")
#> [1] 1000
```

<sup>Created on 2022-05-30 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

Is there another example that illustrates this point?

**Comment by PavelBal** [comment]
This is because `g/kg` has been added to the list of supported units (yey).

The following code produces an error: 

```
toUnit(quantityOrDimension = ospDimensions$`Dose per body weight`, values = 1, targetUnit = "g/g")

Error in rClr::clrCall(dimensionTask, "ConvertToUnit", dimension, targetUnit,  : 
  Type:    OSPSuite.Utility.Exceptions.OSPSuiteException
Message: Unit 'g/g' is not defined in dimension 'Dose per body weight'.
Method:  Double[] convertToUnit(OSPSuite.Core.Domain.UnitSystem.IDimension, System.String, System.Nullable`1[System.Double], Double[])
Stack trace:
   at OSPSuite.R.Services.DimensionTask.convertToUnit(IDimension dimension, String targetUnit, Nullable`1 molWeight, Double[] valuesInBaseUnit)
   at OSPSuite.R.Services.DimensionTask.ConvertToUnit(String dimensionName, String targetUnit, Double valueInBaseUnit)
```


However the message makes sense now, so the issue is solved.
