### ISSUE TITLE
Error on initPKSim

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite-R#512]
I keep getting this error when trying to call `initPKSim`:

```
Error in rClr::clrCallStatic("PKSim.R.Api", "InitializeOnce") : 
  Type:    System.ArgumentException
Message: Type OSPSuite.Core.Extensions.TaskExtensions+<SecureAwait>d__2`1[TObject] is not a class nor an interface, and those are the only values allowed.
Method:  Void AddService(System.Collections.Generic.IList`1[System.Type], System.Type)
Stack trace:
   at Castle.Core.Internal.ComponentServicesUtil.AddService(IList`1 existingServices, Type newService)
   at Castle.MicroKernel.Registration.ComponentRegistration`1.Forward(IEnumerable`1 types)
   at Castle.MicroKernel.Registration.ComponentRegistration`1..ctor(Type[] services)
   at Castle.MicroKernel.Registration.Component.For(Type serviceType)
   at Castle.MicroKernel.Registration.Component.For(IEnumerable`1 serviceTypes)
   at OSPSuite.Infrastructure.Container.Castle.CastleWindsorContainer.register(IReadOnlyCollection`1 serviceTypes, Type concreteType, LifeStyle lifeStyle, String key)
   at OSPSuite.Infrastructure.Container.Castle.CastleWindsorContainer.Register(IReadOnlyCollection`1 serv
```

I have the libraries from the latest ospuite-r build (https://ci.appveyor.com/project/open-systems-pharmacology-ci/ospsuite-r/builds/38734249/artifacts) and OSPSuite.Core and OSPSuite.R from the current develop-branch of Core.

**Comment by msevestre** [comment]
@PavelBal I am pretty sure that this is because or Dlls are not compatible. Once we ensure that PKSim uses the same version, we should be good
