### ISSUE TITLE
Cannot load data repository exported with PKSim V10

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite-R#573]
PKSim V10.0.198, imported observed data and exported it to PKML. Trying to load it in R results in

```
Error in rClr::clrCall(dataRepositoryTask, "LoadDataRepository", filePath) : 
  Type:    OSPSuite.Utility.Exceptions.OSPSuiteException
Message: PKML file is too old and cannot be converted. Please install the version 8.0 of the OSPSuite to convert the file to a version that can be supported
Method:  Void convert[T](T, Int32, System.Func`2[OSPSuite.Core.Converters.IObjectConverter,System.Func`2[T,System.ValueTuple`2[System.Int32,System.Boolean]]])
Stack trace:
   at OSPSuite.Core.Serialization.Xml.PKMLPersistor.convert[T](T objectToConvert, Int32 objectVersion, Func`2 converterAction)
   at OSPSuite.Core.Serialization.Xml.PKMLPersistor.convertXml(XElement sourceElement, Int32 version)
   at OSPSuite.Core.Serialization.Xml.PKMLPersistor.Load[T](String pkmlFileFullPath, IDimensionFactory dimensionFactory, IObjectBaseFactory objectBaseFactory, IWithIdRepository withIdRepository, ICloneManagerForModel cloneManagerForModel)
   at OSPSuite.R.Services.DataRepositoryTask.LoadDataRepository(String fileName)
```

**Comment by msevestre** [comment]
File too old... interesting...it should be converted to the new version. Can you share the project?

**Comment by PavelBal** [comment]
It is a new (empty) PKsim project, just imported this file for testing and
exported the data as pkml

Michael Sevestre ***@***.***> schrieb am Fr., 6. Aug. 2021,
15:26:

**Comment by msevestre** [comment]
Ok I just need the pkml file then :)_

**Comment by PavelBal** [comment]
`<McDataRepository id="331f4870-bf18-4c68-8e9c-1df5b1466e1d" name="CompiledDataSet.TestSheet_1.ID01.PeripheralVenousBlood.Plasma.Human.Female.Dapagliflozin.iv" icon="ObservedData" configurationId="44dc7b47-4eb5-443d-a21b-8b499bfe906e">`

The property `version` is not present at all.

The file can be loaded in MoBi.
[obs_data_lloq.zip](https://github.com/Open-Systems-Pharmacology/OSPSuite-R/files/6946449/obs_data_lloq.zip)

**Comment by msevestre** [comment]
This is a very very old obs data file lol

**Comment by PavelBal** [comment]
Nope, I created it today with V10 PKSim.

**Comment by msevestre** [comment]
Just that I get it straight
You exported some observedata in pksim as pkml and it looked like this? This is a bug theb

**Comment by PavelBal** [comment]
Yepp.

Michael Sevestre ***@***.***> schrieb am Fr., 6. Aug. 2021,
22:12:

**Comment by msevestre** [comment]
Moving to core.
