### ISSUE TITLE
SimulationRunOptions$checkForNegativeValues = FALSE does not work

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite-R#609]
Setting the property `checkForNegativeValues = FALSE` does not allow to simulate when values become negative. Example:

```
sim <- loadTestSimulation(simulationName = "S1", loadFromCache = FALSE)
simResults <- runSimulation(sim) #Works

compartmentMoleculePath <- getMolecule(path = "Organism|ArterialBlood|Plasma|Caffeine", container = sim)
#Set initial value of a molecule to a negative value
setMoleculeInitialValues(compartmentMoleculePath, values = -1)
#Create simulation run options with the option to ignore the negative values check
simRunOptions = SimulationRunOptions$new(checkForNegativeValues = FALSE)
simResults <- runSimulation(simulation = sim, simulationRunOptions = simRunOptions)

 Error in rClr::clrCall(simulationRunner, "Run", simulationRunArgs) : 
  Type:    OSPSuite.Utility.Exceptions.OSPSuiteException
Message: Initial value of S1|Organism|ArterialBlood|Plasma|Caffeine is negative, but it was marked as positive.
Please check your model
Method:  Void RunSimulation()
Stack trace:
   at OSPSuite.SimModel.Simulation.RunSimulation()
   at OSPSuite.Core.Domain.Services.SimModelManager.simulate()
   at OSPSuite.Core.Domain.Services.SimModelManager.doIfNotCanceled(Action actionToExecute)
   at OSPSuite.Core.Domain.Services.SimModelManager.RunSimulation(IModelCoreSimulation simulation, SimulationRunOptions simulationRunOptions)
   at OSPSuite.R.Services.SimulationRunner.<>c__DisplayClass13_0.<runAsync>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute() 
4.
rClr::clrCall(simulationRunner, "Run", simulationRunArgs) at utilities-simulation.R#211
3.
.runSingleSimulation(simulation = simulations[[1]], simulationRunOptions = simulationRunOptions, 
    population = population, agingData = agingData) at utilities-simulation.R#166
2.
runSimulations(simulations = simulation, population = population, 
    agingData = agingData, simulationRunOptions = simulationRunOptions) at utilities-simulation.R#117
1.
runSimulation(simulation = sim, simulationRunOptions = simRunOptions) 

```

@msevestre @Yuri05

**Comment by Yuri05** [comment]
@PavelBal At least you get a good error message 😉 

It happens in fact only when the **initial** value is negative (forgotten to check for the global option in this case):
https://github.com/Open-Systems-Pharmacology/OSPSuite.SimModel/blob/a2a2b8906878f0f6c35b584835c2848e194f1e95/src/OSPSuite.SimModelNative/src/Simulation.cpp#L759-L767

**Comment by PavelBal** [comment]
Yepp, you're right, the other one was a bug in my code :D

**Comment by PavelBal** [comment]
This is still a bug for initial values - should the issue be movd to SimModel?
