### ISSUE TITLE
'System.Collections.Generic.KeyNotFoundException' error after RStudio update

### ISSUE THREAD

**Issue by IndrajeetPatil** [Open-Systems-Pharmacology/OSPSuite-R#683]
I was using an old version of RStudio and I updated it today, and `{ospsuite}` no longer seems to load.

The error I see is:

```r
Error in rClr::clrCall(dimensionTask, "AllAvailableUnitNamesFor", enc2utf8(dimension)) : 
Type: System.Collections.Generic.KeyNotFoundException
Message: Dimension 'CV mmHg*sÂ²/ml' not available in DimensionFactory.
Method: OSPSuite.Core.Domain.UnitSystem.IDimension Dimension(System.String)
Stack trace:
at OSPSuite.Core.Domain.UnitSystem.DimensionFactory.Dimension(String name)
at OSPSuite.R.Services.DimensionTask.DimensionByName(String dimensionName)
at OSPSuite.R.Services.DimensionTask.AllAvailableUnitNamesFor(String dimensionName)
```

Traceback:

```r
13. rClr::clrCall(dimensionTask, "AllAvailableUnitNamesFor", enc2utf8(dimension)) at utilities-units.R#244
12. getUnitsForDimension(dimension = dimension) at utilities-units.R#280
11. FUN(X[[i]], ...)
10. lapply(dimensions, function(dimension) {
x <- getUnitsForDimension(dimension = dimension)
return(enum(replace(x, x == "", "Unitless")))
}) at utilities-units.R#279
9. getUnitsEnum() at utilities-units.R#312
8. initializeDimensionAndUnitLists() at init-package.R#23
7. initPackage() at zzz.R#9
6. nsenv[[f_name]](dirname(ns_path), package)
5. run_pkg_hook(package, "load")
4. pkgload::load_all(path, helpers = FALSE, attach_testthat = FALSE)
3. load_code(base_path)
2. roxygen2::roxygenise(pkg$path, roclets)
1. devtools::document()
```

Off the top of your head, can you think of a way to solve this?  If not, I can just revert to the old version I was using.

It is quite odd though that an IDE update would cause an issue like this.

**Comment by msevestre** [comment]
I just installed R Studio last week. No problem. So it's maybe the R version assoaciated?

**Comment by msevestre** [comment]
![image](https://user-images.githubusercontent.com/1041237/145232121-6e4a12c9-79f9-45ae-811f-47597a5d6c5f.png)

**Comment by IndrajeetPatil** [comment]
Turns out I downloaded the development version of RStudio, and not the stable build 🐒 

I don't see this issue with the stable build.
