### ISSUE TITLE
Update website

### ISSUE THREAD

**Issue by IndrajeetPatil** [Open-Systems-Pharmacology/OSPSuite-R#773]
@msevestre Can you please update package website? A lot has changed since the last time it was built. 

You just need to run:

```r
pkgdown::build_site()
```

I would do this, but I keep getting _PK installation not found_ error, and I don't have time to figure out how to resolve that problem.

**Comment by IndrajeetPatil** [comment]
@Yuri05 Wanna also take care of this one?

**Comment by Yuri05** [comment]
can do :)

**Comment by Yuri05** [comment]
cannot build the website locally. I don't have a PK-Sim 11 installation and `initPKsim()` (called by CreateIndividual/CreatePopulation in the vignettes) fails.

I temporarily changed the `initPKsim()` function so that it takes my PK-Sim 11 portable and tried to compile the package locally, but then  I get weird errors (s. below) which I don't have time to investigate.

```
> devtools::build()
√  checking for file 'C:\SW-Dev\OSPSuite-R/DESCRIPTION' (563ms)
-  preparing 'ospsuite': (7.2s)
√  checking DESCRIPTION meta-information ... 
-  installing the package to build vignettes (673ms)
E  creating vignettes (1m 4.8s)
   --- re-building 'create-individual.Rmd' using rmarkdown
   Quitting from lines 30-49 (create-individual.Rmd) 
   Error: processing vignette 'create-individual.Rmd' failed with diagnostics:
   Type:    System.Reflection.ReflectionTypeLoadException
   Message: Mindestens ein Typ in der Assembly kann nicht geladen werden. Rufen Sie die LoaderExceptions-Eigenschaft ab, wenn Sie weitere Informationen benötigen.
   Method:  System.RuntimeType[] GetTypes(System.Reflection.RuntimeModule)
   Stack trace:
      bei System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
      bei System.Reflection.Assembly.GetTypes()
      bei OSPSuite.Utility.Container.AssemblyScanner.scanTypesInAssembly(Assembly assembly)
   
   Type:    System.TypeLoadException
   Message: Die Methode "CalculateFor" im Typ "PKSim.Core.Model.UnknownDistributionFormula" der Assembly "PKSim.Core, Version=11.0.82.0, Culture=neutral, PublicKeyToken=null" hat keine Implementierung.
   Method:  
   Stack trace:
   
   --- failed re-building 'create-individual.Rmd'
   
   --- re-building 'create-run-population.Rmd' using rmarkdown
   Quitting from lines 38-61 (create-run-population.Rmd) 
   Error: processing vignette 'create-run-population.Rmd' failed with diagnostics:
   Type:    System.Reflection.ReflectionTypeLoadException
   Message: Mindestens ein Typ in der Assembly kann nicht geladen werden. Rufen Sie die LoaderExceptions-Eigenschaft ab, wenn Sie weitere Informationen benötigen.
   Method:  System.RuntimeType[] GetTypes(System.Reflection.RuntimeModule)
   Stack trace:
      bei System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
      bei System.Reflection.Assembly.GetTypes()
      bei OSPSuite.Utility.Container.AssemblyScanner.scanTypesInAssembly(Assembly assembly)
   
   Type:    System.TypeLoadException
   Message: Die Methode "CalculateFor" im Typ "PKSim.Core.Model.UnknownDistributionFormula" der Assembly "PKSim.Core, Version=11.0.82.0, Culture=neutral, PublicKeyToken=null" hat keine Implementierung.
   Method:  
   Stack trace:
   
   --- failed re-building 'create-run-population.Rmd'
```

**Comment by msevestre** [comment]
I can do this

**Comment by msevestre** [comment]
I have the same error...

-- RMarkdown error -------------------------------------------------------------
Quitting from lines 30-49 (create-individual.Rmd) 
Error in rClr::clrCallStatic("PKSim.R.Api", "InitializeOnce") : 
  Type:    System.Reflection.ReflectionTypeLoadException
Message: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
Method:  System.RuntimeType[] GetTypes(System.Reflection.RuntimeModule)
Stack trace:
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at OSPSuite.Utility.Container.AssemblyScanner.scanTypesInAssembly(Assembly assembly)

Type:    System.TypeLoadException
Message: Method 'CalculateFor' in type 'PKSim.Core.Model.UnknownDistributionFormula' from assembly 'PKSim.Core, Version=11.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method:  
Stack trace:



--------------------------------------------------------------------------------
Error : Failed to render RMarkdown
Error: callr subprocess failed: Failed to render RMarkdown
Type .Last.error.trace to see where the error occurred

I am not sure what this means. Probably an outdated version of a DLL in one of the components.. but I am not sure why... it looks like the wrong dll is being loaded in the package when using pkgdown. I'll try again later today (tomorrow)

**Comment by PavelBal** [comment]
I still cannot run `initPKSim()` locally - latest PKSim nightly, so something is wrong with the library versions.

**Comment by msevestre** [comment]
the dll are completely outdated in core. (like version of 2 months ago). SOmething went wrong in one of the merge. I have made a PR to fix this

**Comment by msevestre** [comment]
I am getting this error
![image](https://user-images.githubusercontent.com/1041237/155543188-5cff4994-ca64-4b35-8d9a-3fa084e9a52e.png)

any idea?

**Comment by IndrajeetPatil** [comment]
You mean `"Vignette missing..."` warning? You can ignore it. It's because we are using that vignette as a "Get Started" vignette.
Somehow _pkgdown_ supports this feature but doesn't anticipate it.

**Comment by msevestre** [comment]
>Somehow pkgdown supports this feature but doesn't anticipate it.

lol.
