### ISSUE TITLE
`DataRepository` created in R cannot be opened in MoBi.

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite-R#775]
When creating an empty `DataSet` in R, we do

`dataSet1 <- ospsuite::DataSet$new(name = "data1")`

this creates an empty `DataRepository` by calling  `rClr::clrNew("OSPSuite.Core.Domain.Data.DataRepository")`. When this `DataSet` is saved as PKML, it can be loaded in MoBi, but trying to open it throws the error

Application:
MoBi® 10.0.122

Object reference not set to an instance of an object.

Stack trace:
```
at OSPSuite.Presentation.Presenters.ObservedData.DataRepositoryChartPresenter.plotObservedData(DataRepository dataRepository)
   at OSPSuite.Presentation.Presenters.ObservedData.DataRepositoryChartPresenter.EditObservedData(DataRepository observedData)
   at OSPSuite.Presentation.Presenters.ObservedData.EditDataRepositoryPresenter.<>c__DisplayClass8_0.<Edit>b__0(IDataRepositoryItemPresenter presenter)
   at OSPSuite.Utility.Extensions.EnumerableExtensions.Each[T](IEnumerable`1 list, Action`1 action)
   at OSPSuite.Presentation.Presenters.ObservedData.EditDataRepositoryPresenter.Edit(DataRepository repositoryToEdit)
   at OSPSuite.Presentation.Presenters.SubjectPresenter`3.Edit(Object objectToEdit)
   at MoBi.Presentation.UICommand.EditObservedDataUICommand.PerformExecute()
   at OSPSuite.Presentation.UICommands.ObjectUICommand`1.Execute()
   at OSPSuite.Presentation.UICommands.UICommandExtensions.ExecuteWithinExceptionHandler(IUICommand uiCommand, IEventPublisher eventPublisher, IChangePropagator changePropagator)
```

Georgios did debug this and says

> [Yesterday 20:03] Georgios Daskalakis
> you have to change in the column
> 
> [Yesterday 20:03] Georgios Daskalakis
> <DataInfo origin="Observation"
> 
> [Yesterday 20:04] Georgios Daskalakis
> instead of ObservationAuxiliary or Undefined
> 

I think this must be done automatically when creating an empty date repository from R.

@msevestre I think this is more core than R, but not sure how this should be solved.

**Comment by msevestre** [comment]
I'll check it out. Do we create columns in R automatically when creating a new DataSEt?

**Comment by PavelBal** [comment]
Yes:

```
      # Passing time for dimension for now
      xColumn <- DataColumn$new(
        rClr::clrNew(
          "OSPSuite.Core.Domain.Data.BaseGrid",
          "xValues",
          getDimensionByName(ospDimensions$Time)
        )
      )

      # Passing concentration (mass) for dimension for now
      yColumn <- DataColumn$new(
        rClr::clrNew(
          "OSPSuite.Core.Domain.Data.DataColumn",
          "yValues",
          getDimensionByName(ospDimensions$`Concentration (mass)`),
          xColumn$ref
        )
      )
```
