### ISSUE TITLE
`setParameterValuesByPath` fails if the path cannot be found if a unit is provided, even if `stopIfNotFound = FALSE`

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite-R#807]
Test: 

```
  sim <- loadTestSimulation("S1", loadFromCache = TRUE)
  parameterPath <- "foo"
  setParameterValuesByPath(parameterPath, 100, sim, stopIfNotFound = FALSE, units = "l")

Error in rClr::clrCall(task, "DimensionNameByPath", simulation$ref, path) : 
Type: OSPSuite.Utility.Exceptions.OSPSuiteException
Message: Could not find quantity with path 'foo'.
Method: OSPSuite.Core.Domain.IQuantity singleQuantityByPath(OSPSuite.Core.Domain.IModelCoreSimulation, System.String)
Stack trace:
at OSPSuite.R.Services.ContainerTask.singleQuantityByPath(IModelCoreSimulation simulation, String path)
at OSPSuite.R.Services.ContainerTask.DimensionNameByPath(IModelCoreSimulation simulation, String path)
3.
rClr::clrCall(task, "DimensionNameByPath", simulation$ref, path) at utilities-quantity.R#158
2.
setQuantityValuesByPath(quantityPaths = parameterPaths, values = values, 
simulation = simulation, units = units, stopIfNotFound = stopIfNotFound) at utilities-parameter.R#128
1.
setParameterValuesByPath(parameterPath, 100, sim, stopIfNotFound = FALSE, 
units = "l")
```

**Comment by msevestre** [comment]
see https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/issues/1533
