### ISSUE TITLE
createIndividual fails if no population is provided.

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite-R#816]
It is possible to create `IndividualCharactersitics` without population, but the subsequent `createIndividual` fails. I think this shoul be restricted in IndividualCharacterstics

```
> individualCharacteristics <- createIndividualCharacteristics(species = Species$Human, height = NULL)
> individual <- createIndividual(individualCharacteristics)
Error in rClr::clrCall(individualFactory, "CreateIndividual", individualCharacteristics$ref) : 
  Type:    PKSim.Core.PKSimException
Message: Could not find population '' for species 'Human'.
Available populations are:
	European_ICRP_2002
	WhiteAmerican_NHANES_1997
	BlackAmerican_NHANES_1997
	MexicanAmericanWhite_NHANES_1997
	Asian_Tanaka_1996
	Preterm
	Japanese_Population
	Pregnant
Method:  PKSim.Core.Model.SpeciesPopulation speciesPopulationFrom(PKSim.Core.Snapshots.OriginData, PKSim.Core.Model.Species)
Stack trace:
   at PKSim.Core.Snapshots.Mappers.OriginDataMapper.speciesPopulationFrom(OriginData snapshot, Species species)
   at PKSim.Core.Snapshots.Mappers.OriginDataMapper.MapToModel(OriginData snapshot)
   at PKSim.R.Services.IndividualFactory.originDataFrom(OriginData originData)
   at PKSim.R.Services.IndividualFactory.CreateIndividual(IndividualCharacteristics individualCharacteristics)
```

**Comment by msevestre** [comment]
Hard. The check is done in PKSim. Individual characteristics is just a parameter container. Typically one is used after the other so the gain would be limited

**Comment by PavelBal** [comment]
At least we could check that Population is not empty when Species is human?

**Comment by msevestre** [comment]
Yes that can be done in R

**Comment by Yuri05** [comment]
We have all human populations cached in R, could use this for check?

```
> ospsuite::HumanPopulation
$Asian_Tanaka_1996
[1] "Asian_Tanaka_1996"

$BlackAmerican_NHANES_1997
[1] "BlackAmerican_NHANES_1997"

$European_ICRP_2002
[1] "European_ICRP_2002"

$Japanese_Population
[1] "Japanese_Population"

$MexicanAmericanWhite_NHANES_1997
[1] "MexicanAmericanWhite_NHANES_1997"

$Pregnant
[1] "Pregnant"

$Preterm
[1] "Preterm"

$WhiteAmerican_NHANES_1997
[1] "WhiteAmerican_NHANES_1997"

```
