### ISSUE TITLE
`DataSet$setValues` fails when only one data point is set

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite-R#896]
```
ds1 <- DataSet$new(name = "Sim1")
ds1$setValues(xValues = 0, yValues = 1, yErrorValues = 2.747)

Error in clrCallStatic(clrFacadeTypeName, "SetFieldOrProperty", objOrType, : 
Type: System.ArgumentException
Message: Object of type 'System.Double' cannot be converted to type 'System.Double[]'.
Method: System.Object TryChangeType(System.Object, System.Reflection.Binder, System.Globalization.CultureInfo, Boolean)
Stack trace:
at System.RuntimeType.TryChangeType(Object value, Binder binder, CultureInfo culture, Boolean needsSpecialCast)
at System.Reflection.MethodBase.CheckArguments(Object[] parameters, Binder binder, BindingFlags invokeAttr, CultureInfo culture, Signature sig)
at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
at System.Reflection.RuntimePropertyInfo.SetValue(Object obj, Object value, Object[] index)
at Rclr.ClrFacade.SetFieldOrProperty(Object obj, String name, Object value)
6.
clrCallStatic(clrFacadeTypeName, "SetFieldOrProperty", objOrType, 
name, value)
5.
rClr::clrSet(self$ref, propertyName, value) at dot-net-wrapper.R#47
4.
private$wrapProperty("ValuesAsArray", value) at data-column.R#15
3.
(function (value) 
{
private$wrapProperty("ValuesAsArray", value)
})(base::quote(0)) at data-set.R#297
2.
private$.setColumnValues(column = private$.xColumn, xValues) at data-set.R#243
1.
ds1$setValues(xValues = 0, yValues = 1, yErrorValues = 2.747)
```

This fails in core here:  

```
     /// <summary>
      ///    Required for R
      /// </summary>
      public virtual double[] ValuesAsArray
      {
         get => Values?.ToDoubleArray() ?? Array.Empty<double>();
         set => Values = value?.ToFloatArray();
      }
```

We need a function to set single values (how ugly, yes).

**Comment by msevestre** [comment]
@IndrajeetPatil Let's fix that tomorrow to as part of the DLL update. We'll have to fix both probably in one PR for the tests to run (or at least do the other one first)
